name: Node.js CI

on:
  push:
    branches:
      - development
  pull_request:

jobs:
  lint_test_build:
    name: Lint, test and build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Read .nvmrc
        id: nvm
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"

      - name: Prepare release notes
        id: release_notes
        run: |
          CHANGELOG=$(awk "/## \[Unreleased\]/ {flag=1;next} /## \[/ {flag=0} flag {print}" CHANGELOG.md)
          CHANGELOG="${CHANGELOG//'%'/'%25'}"
          CHANGELOG="${CHANGELOG//$'\n'/'%0A'}"
          CHANGELOG="${CHANGELOG//$'\r'/'%0D'}"
          echo ::set-output name=RELEASE_NOTES::$CHANGELOG

      - name: read release notes
        run: echo "${{ steps.release_notes.outputs.RELEASE_NOTES }}"
