name: Create Pre-Release

on:
  push:
    tags:
      - "v*.*.*-*"
  pull_request:

jobs:
  lint_test_build_pre_release:
    name: Lint, test, build and create pre-release
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true || "startsWith(GITHUB_REF, 'refs/tags/v')"
    steps:
      - name: Setup Git User
        run: |
          git config --global user.email "github-actions-ci@tokyodrift1993.org"
          git config --global user.name "Github Actions CI"

      - name: Checkout
        uses: actions/checkout@v2

      - name: Read .nvmrc
        id: nvm
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Create Pre-Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: true
