name: Create Pre-Release

on:
  pull_request:
    types: [closed]

jobs:
  lint_test_build_pre_release:
    name: Lint, test, build and create pre-release
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Setup git user
        run: |
          git config --global user.name "Github Actions CI"
          git config --global user.email "github-actions-ci@tokyodrift1993.org"

      - name: Checkout
        uses: actions/checkout@v2

      - name: Read .nvmrc
        id: nvm
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Prepare version
        run: yarn version --prerelease --cwd ./.ci

      - name: Read version
        id: read_version
        run: |
          echo ::set-output name=VERSION::$(yarn versions --json --cwd ./.ci | jq -r '.data."@tokyodrift1993/testing-github-actions"')
          echo "::set-output name=TAG::v$(yarn versions --json --cwd ./.ci | jq -r '.data."@tokyodrift1993/testing-github-actions"')"

      - name: Bump version
        run: yarn version --new-version ${{ steps.read_version.outputs.VERSION }} --no-git-tag-version

      - name: Prepare release notes
        id: release_notes
        run: echo ::set-output name=RELEASE_NOTES::$(awk "/## \[Unreleased\]/ {flag=1;next} /## \[/ {flag=0} flag {print}" CHANGELOG.md)

      - name: Create GitHub Release Notes
        id: create_github_release_notes
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_PAT }}
        with:
          tag_name: ${{ steps.read_version.outputs.TAG }}
          release_name: Release ${{ steps.read_version.outputs.TAG }}
          body: ${{ steps.release_notes.outputs.RELEASE_NOTES }}
          draft: false
          prerelease: true

      - name: Commit release TAG
        run: |
          git commit -am "${{ steps.read_version.outputs.TAG }}"
          git push

#      - name: Publish npm
#        id: publish_npm
#      - run: |
#          cd ./dist
#          yarn publish --tag next --new-version ${{ steps.read_version.outputs.VERSION }}
#        env:
#          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
